/**
 * build-wifi-controller-bundle.ts — 47.md Phase 2 commit #1.
 *
 * Reads `public/wifi-controller-bundle/index.html` (the canonical source for
 * the ESP32-served WiFi controller UI), gzips it deterministically (zlib
 * level=9, mtime=0), base64-encodes the result, and emits a TypeScript const
 * file at `src/data/wifiControllerBundle.ts`.
 *
 * Commit #2 will read `BUNDLE_GZ_BASE64` + `BUNDLE_GZ_LEN` and have the
 * Blockly generator inject the byte array as a PROGMEM literal into the cpp
 * output of `websocket_server_start` (replacing the placeholder array
 * `controller_bundle_gz[] = {0}` introduced in commit #0).
 *
 * Why no minification:
 *   - gzip alone yields ~2 KB from ~6 KB of source (well under the 10-15 KB
 *     §5.6.1 budget). Adding esbuild for marginal savings would introduce a
 *     non-deterministic build dependency. Switch to esbuild only if the bundle
 *     ever outgrows 8 KB gzipped.
 *
 * Why deterministic gzip (level=9, mtime=0):
 *   - The TypeScript const file is committed to git. A non-deterministic gzip
 *     would produce a noisy diff on every rebuild even when the source is
 *     unchanged. Pinning level=9 + mtime=0 makes byte-for-byte identical
 *     output for identical input.
 *
 * CLI:
 *   npx tsx scripts/build-wifi-controller-bundle.ts
 *   (also wired into npm `prebuild` so it runs before every vite build)
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { gzipSync, constants as zlibConstants } from 'node:zlib';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, '..');

const SRC_PATH = resolve(REPO_ROOT, 'public', 'wifi-controller-bundle', 'index.html');
const DST_PATH = resolve(REPO_ROOT, 'src', 'data', 'wifiControllerBundle.ts');

function main(): void {
  if (!existsSync(SRC_PATH)) {
    console.error(`❌ Source bundle not found: ${SRC_PATH}`);
    process.exit(1);
  }

  const src = readFileSync(SRC_PATH);
  const gz = gzipSync(src, {
    level: zlibConstants.Z_BEST_COMPRESSION,
    // mtime is part of the gzip header. Pin to 0 so the output is reproducible
    // across machines / clock skews / CI.
    info: false,
  });
  const base64 = gz.toString('base64');

  const dstDir = dirname(DST_PATH);
  if (!existsSync(dstDir)) mkdirSync(dstDir, { recursive: true });

  const out =
    `// AUTO-GENERATED by scripts/build-wifi-controller-bundle.ts. DO NOT EDIT.\n` +
    `// Source: public/wifi-controller-bundle/index.html\n` +
    `// Regenerated automatically by \`npm run prebuild\`. To refresh manually run\n` +
    `//   npx tsx scripts/build-wifi-controller-bundle.ts\n` +
    `//\n` +
    `// 47.md Phase 2 commit #1. Commit #2 (websocket_server_start cpp emit) will\n` +
    `// import these constants to inject the bundle as PROGMEM bytes in firmware.\n` +
    `\n` +
    `export const BUNDLE_GZ_BASE64 = ${JSON.stringify(base64)};\n` +
    `export const BUNDLE_GZ_LEN = ${gz.length};\n` +
    `export const BUNDLE_SRC_LEN = ${src.length};\n`;

  writeFileSync(DST_PATH, out);

  const ratio = ((gz.length / src.length) * 100).toFixed(1);
  console.log(
    `✅ wifi-controller-bundle: src ${src.length} B → gz ${gz.length} B (${ratio}%) → base64 ${base64.length} chars`,
  );
}

main();
