/**
 * build-unified-controller-bundle.ts — 47.md Phase 3 / 48.md commit #1.
 *
 * Reads `public/unified-controller-bundle/index.html` (the canonical source
 * for the file:// distributable unified controller bundle), guards it against
 * a 15 KB gzipped budget, and emits a TypeScript const file at
 * `src/data/unifiedControllerBundle.ts` exporting the raw HTML template.
 *
 * Why raw template (not gzipped base64 like Phase 2):
 *   - Phase 2 bundle is consumed by ESP32 firmware as PROGMEM bytes — gzip
 *     base64 minimizes flash footprint.
 *   - Phase 3 bundle is consumed by frontend JS (`unifiedControllerBuilder.ts`,
 *     commit #2) which performs runtime string replacement on the
 *     `<script id="schema" type="application/json">{}</script>` placeholder
 *     before wrapping the result in a Blob for download. String replacement
 *     on the raw template is straightforward; gzipping at build time would
 *     force a runtime decompress + re-encode that buys nothing.
 *
 * The 15 KB gz size assertion (48.md §I5) is computed for monitoring only —
 * if the bundle ever balloons past ~9 KB gz (the empirical estimate for
 * N=10 devices), this is the early-warning trip.
 *
 * CLI:
 *   npx tsx scripts/build-unified-controller-bundle.ts
 *   (also wired into npm `prebuild` so it runs before every vite build)
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { gzipSync, constants as zlibConstants } from 'node:zlib';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, '..');

const SRC_PATH = resolve(REPO_ROOT, 'public', 'unified-controller-bundle', 'index.html');
const DST_PATH = resolve(REPO_ROOT, 'src', 'data', 'unifiedControllerBundle.ts');
const GZ_BUDGET_BYTES = 15 * 1024;

function main(): void {
  if (!existsSync(SRC_PATH)) {
    console.error(`❌ Source bundle not found: ${SRC_PATH}`);
    process.exit(1);
  }

  const srcBuf = readFileSync(SRC_PATH);
  const src = srcBuf.toString('utf8');
  const gz = gzipSync(srcBuf, { level: zlibConstants.Z_BEST_COMPRESSION });

  if (gz.length > GZ_BUDGET_BYTES) {
    console.error(
      `❌ Unified bundle gz size ${gz.length} B exceeds ${GZ_BUDGET_BYTES} B (15 KB) budget`,
    );
    process.exit(1);
  }

  const dstDir = dirname(DST_PATH);
  if (!existsSync(dstDir)) mkdirSync(dstDir, { recursive: true });

  // JSON.stringify produces a TS-valid string literal with all escapes (\n,
  // backslash, embedded quotes) handled correctly. The generated module has
  // no runtime dependencies, so it imports cleanly into both the app and
  // vitest's node environment.
  const out =
    `// AUTO-GENERATED by scripts/build-unified-controller-bundle.ts. DO NOT EDIT.\n` +
    `// Source: public/unified-controller-bundle/index.html\n` +
    `// Regenerated automatically by \`npm run prebuild\`. To refresh manually run\n` +
    `//   npx tsx scripts/build-unified-controller-bundle.ts\n` +
    `//\n` +
    `// 47.md Phase 3 / 48.md commit #1. unifiedControllerBuilder (commit #2)\n` +
    `// imports UNIFIED_BUNDLE_TEMPLATE and string-replaces the inline schema\n` +
    `// placeholder before returning a Blob for download.\n` +
    `\n` +
    `export const UNIFIED_BUNDLE_TEMPLATE = ${JSON.stringify(src)};\n` +
    `export const UNIFIED_BUNDLE_SRC_LEN = ${src.length};\n` +
    `export const UNIFIED_BUNDLE_GZ_LEN = ${gz.length};\n` +
    `export const UNIFIED_BUNDLE_GZ_BUDGET = ${GZ_BUDGET_BYTES};\n`;

  writeFileSync(DST_PATH, out);

  const ratio = ((gz.length / src.length) * 100).toFixed(1);
  const budgetUsed = ((gz.length / GZ_BUDGET_BYTES) * 100).toFixed(1);
  console.log(
    `✅ unified-controller-bundle: src ${src.length} B → gz ${gz.length} B (${ratio}%, ${budgetUsed}% of 15 KB budget)`,
  );
}

main();
