server:
  public:
    address: ":8080"

database:
  host: postgres.railway.internal
  port: 5432
  database: railway
  user: postgres
  password: [POSTGRES_PASSWORD_REDACTED]
  dialect: postgres

webauthn:
  relying_party:
    id: "digicode.pages.dev"
    display_name: "DigiCode"
    origins:
      - "https://digicode.pages.dev"
      - "http://localhost:5173"

secrets:
  keys:
    - RRd4AlsTy2iQ412bxYhl93Hb2mAJdSH+RYL7QIHhyLc=

session:
  lifespan: 12h
  cookie:
    secure: true
    same_site: strict

emails:
  require_verification: true
  smtp:
    host: smtp.resend.com
    port: 587

passcode:
  email:
    from_address: "noreply@digicode.pages.dev"
    from_name: "DigiCode"
